### ISSUE TITLE
Power state in Homekit cannot update correctly by the state of real power sensor

### ISSUE THREAD

**Issue by larisalee** [smartHomeHub/SmartIR#202]
**Home Assistant version**
0.96.5
**SmartIR version**
1.7.1
**SmartIR configuration**
- platform: smartir
  name: Living AC
  unique_id: living_ac
  device_code: 9998
  controller_data: 192.168.1.26
  temperature_sensor: sensor.temperature
  humidity_sensor: sensor.humidity
  power_sensor: binary_sensor.acpower_sensor (I use xiaomi door window sensor to monitor the state)

**Describe the bug**

The power state in Apple Homekit cannot update correctly by power sensor.
If I turn on the ac from my real remote, the SmartIR panel will change its showing state to "on", but in Homekit its state still shows 'off'. 

**Additional context**
3 months ago I reported a similar issue
https://github.com/smartHomeHub/SmartIR/issues/127
Now  the issue has been fixed but in Homekit it still keeps buggy.

**Comment by smartHomeHub** [comment]
Hi, thanks for sharing this. I'm trying to find a solution.

**Comment by tyjtyj** [comment]
I am trying to update power state from sensor. 
I am getting state on instead of cool. 

Looking at the configuration, it say
`power_sensor: binary_sensor.ac_power`

I suggest instead of binary sensor, allow sensor and let user write template to decide it is cool,heat,off

eg. 
sensor.ac_power shows cool when ambient temperate higher than climate.temperature attribute
sensor.ac_power shows heat when ambient temperate lower than climate.temperature attribute
sensor.ac_power shows off when there is no power load

My python not very good not sure if the logic make sense below

```
    async def _async_power_sensor_changed(self, entity_id, old_state, new_state):
        """Handle power sensor changes."""
        if new_state is None:
            return

        if new_state.state != self._hvac_mode:
            self._on_by_remote = True
            self._hvac_mode = new_state.state
            await self.async_update_ha_state()

        if new_state.state == HVAC_MODE_OFF:
            self._on_by_remote = False
            if self._hvac_mode != HVAC_MODE_OFF:
                self._hvac_mode = HVAC_MODE_OFF
            await self.async_update_ha_state()
```
