### ISSUE TITLE
New RM Mini 4 not working

### ISSUE THREAD

**Issue by cubilon** [smartHomeHub/SmartIR#255]
Hi, dunno if it's a SmartIR problem or what, but seems like the new RM4 is not working.
I've opened an issue @ HA: https://github.com/home-assistant/home-assistant/issues/29215

Anyone has evidences of this problem?

(mean this one: https://www.ibroadlink.com/products/ir-control )

**Comment by ArchGalileu** [comment]
For me too ;(

Best regards
ArchGalileu

**Comment by cubilon** [comment]
hey @smartHomeHub, can we help in some way?

**Comment by aferraz** [comment]
+1

**Comment by trankillity** [comment]
This could be related to an issue that I discovered recently. Devices set up using the newer Broadlink app will not accept a local auth() call. The fix for me was to reset the RM Minis (I have 3s) and set them up in the ihc app. Unfortunately, I don't think that the RM Mini 4 can be set up in the older ihc or e-Control app. You may be able to set them up using the python-broadlink project however.

**Comment by smartHomeHub** [comment]
RM4 uses a different API and is not yet supported by Home Assistant
