### ISSUE TITLE
INI Conversion tool is closed-source, Windows-only

### ISSUE THREAD

**Issue by insertjokehere** [smartHomeHub/SmartIR#47]
I am trying to convert some INI files that were working with the old vpnmaster/homeassistant-custom-components custom component, but the tool to do so is closed-source, and Windows only.

1) Can you please publish the source to the conversion tool in `tools/SmartIR_INI_Converter.zip`?
2) A large proportion of the HomeAssistant community don't run Windows (I run Linux, I know quite a few people use MacOS) - is it possible to port this tool to something more cross-platform?

Thanks

**Comment by smartHomeHub** [comment]
1. No. The purpose of this tool is to quickly convert the old INI files. The application is written in classic .NET and requires Visual Studio to be installed by the user. The publication of the code makes no sense since there will always be a compiled file to quickly make the user work. Publishing the code makes no sense since there will always be a compiled exe for the user to quickly get the job done. For someone who worries there are too many .NET decompilers.

2, Not for now. Participation in this is welcome. I spend a lot of my time on this project mainly to answer questions and fix issues. I'm trying to be as quick as I can. I would like to mention that all the old INI files have already been converted. For users who were experiencing conversion problems and did not want to share their files, I was glad I could do it for them.

**Comment by smartHomeHub** [comment]
Please feel free to contact me if you need any further information otherwise please close this issue.

**Comment by insertjokehere** [comment]
Hi, sorry if I came across as demanding, and thank you for your work. I've managed to get my custom INI files working, will clean them up a bit and post them later
