### ISSUE TITLE
Add local GPIO IR LED support

### ISSUE THREAD

**Issue by XinnGadget** [smartHomeHub/SmartIR#654]
Please, add support for IR LED connected to local GPIO on RaspberryPi (or similar boards).

**Comment by normanr** [comment]
Ahh I think you'd need to configure a Home Assistant service for the IR LED using https://www.home-assistant.io/integrations/shell_command/ (because https://www.home-assistant.io/integrations/lirc/ is for receiving only). There's even an example on that page for setting AC temperature. Then SmartIR would need to add a controller for calling shell_commands (with the name that could be given through controller_data similar to how esphome does it).
